### ISSUE TITLE
Test run error in easy_module_attribute_getter: TypeError: object() takes no parameters 

### ISSUE THREAD

**Issue by M4rt1nM4yr** [KevinMusgrave/powerful-benchmarker#25]
Hello, 

I wanted to run several experiments on your benchmarking system, but unfortunately, the test run doesn't work. 
(python3 run.py --experiment_name test1 --dataset {CUB200: {download: True}})
I use the following versions: 
pytorch 1.4.0
record-keeper 0.9.25
powerful-benchmarker 0.9.25
easy-module-attribute-getter 0.9.37
pytorch-metric-learning 0.9.86
faiss-gpu 1.6.3

The error is:
`
INFO:root:Importing packages in single_experiment_runner
INFO:faiss:Loading faiss with AVX2 support.
INFO:root:Importing packages in base_runner
INFO:root:Done importing packages in base_runner
INFO:root:Done importing packages in single_experiment_runner
INFO:root:NUMPY_RANDOM = RandomState(MT19937)
Using downloaded and verified file: /home/mayr/Documents/datasets/cub2011/CUB_200_2011.tgz
INFO:root:Extracting dataset
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12005/12005 [00:04<00:00, 2868.62it/s]
INFO:root:EMBEDDER MODEL MLP(
  (net): Sequential(
    (0): Linear(in_features=1024, out_features=128, bias=True)
  )
  (last_linear): Linear(in_features=1024, out_features=128, bias=True)
)
INFO:root:Setting dataset so that transform can be set
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    r.run()
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 19, in run
    self.run_new_experiment_or_resume(self.YR)
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 34, in run_new_experiment_or_resume
    return self.start_experiment(args)
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 23, in start_experiment
    run_output = api_parser.run()
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 55, in run
    return self.run_train_or_eval()
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 63, in run_train_or_eval
    self.run_for_each_split_scheme()
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 84, in run_for_each_split_scheme
    self.set_models_optimizers_losses()
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 383, in set_models_optimizers_losses
    self.set_transforms()
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 199, in set_transforms
    transforms = self.get_transforms()
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 193, in get_transforms
    transforms[k] = self.pytorch_getter.get_composed_img_transform(v, **model_transform_properties)
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/easy_module_attribute_getter/pytorch_getter.py", line 39, in get_composed_img_transform
    return self.get_composed_transform(transform_dict)
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/easy_module_attribute_getter/pytorch_getter.py", line 27, in get_composed_transform
    augmentations.append(self.get("transform", k, param))
  File "/home/mayr/anaconda3/envs/dml/lib/python3.6/site-packages/easy_module_attribute_getter/easy_module_attribute_getter.py", line 24, in get
    return uninitialized(**params)
TypeError: object() takes no parameters
`

Do you know what I'm doing wrong?
Thanks for your help!

**Comment by KevinMusgrave** [comment]
Hmm, I tried the command in a google colab notebook and it worked.

Did you make any changes to the config files? If not, what version of PyYAML do you have? 
```python
import yaml
yaml.__version__
```
If it's less than 5.3.1, can you try ```pip install PyYAML==5.3.1```?

**Comment by M4rt1nM4yr** [comment]
I didn't make changes to the config files. I use your example script (run.py). 
If None is the value for root_config_folder, the default configs of the installed package will be used?
PyYAML version is 5.3.1.

**Comment by KevinMusgrave** [comment]
Yeah you can leave root_config_folder as None.

Maybe you can try running this code and see if it works:
```python
import torchvision.transforms.functional as F
from torchvision import transforms
from PIL import Image

class ConvertToBGR(object):
    """
    Converts a PIL image from RGB to BGR
    """

    def __init__(self):
        pass

    def __call__(self, img):
        r, g, b = img.split()
        img = Image.merge("RGB", (b, g, r))
        return img


train = {'Resize': {'size': 256}, 'RandomResizedCrop': {'scale': [0.16, 1], 'ratio': [0.75, 1.33], 'size': 227}, 'RandomHorizontalFlip': {'p': 0.5}}
eval = {'Resize': {'size': 256}, 'CenterCrop': {'size': 227}}

transforms.Resize(**train["Resize"])
transforms.RandomResizedCrop(**train["RandomResizedCrop"])
transforms.RandomHorizontalFlip(**train["RandomHorizontalFlip"])

transforms.Resize(**eval["Resize"])
transforms.RandomResizedCrop(**eval["CenterCrop"])

empty_kwargs = {}
ConvertToBGR(**empty_kwargs)
transforms.ToTensor(**empty_kwargs)

print("success")
```

**Comment by M4rt1nM4yr** [comment]
Thank you for your help. 
I updated to a newer torchvision version (0.4.2) and now it's working fine.
(with torchvision version 0.2.0 it didn't work)

By the way, your paper "A Metric Learning Reality Check" is very good.

**Comment by KevinMusgrave** [comment]
Thanks! Re: torchvision, I didn't realize an older version would break it, so I'll add a minimum version requirement.
