### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/content'

### ISSUE THREAD

**Issue by usuyama** [KevinMusgrave/powerful-benchmarker#59]
Got this error when trying the [getting started script](https://kevinmusgrave.github.io/powerful-benchmarker/)

`python run.py --experiment_name test1 --dataset {CUB200: {download: True}}`

To fix this, just need to specify the experiment folder `--root_experiment_folder experiments`

but we could make the error message or tutorial doc more beginner-friendly.

```
 python run.py --experiment_name test1 --dataset {CUB200: {download: True}}
INFO:root:Importing packages in base_runner
INFO:root:Done importing packages in base_runner
INFO:root:Done importing packages in single_experiment_runner
INFO:faiss:Loading faiss with AVX2 support.
INFO:faiss:Loading faiss.
INFO:root:NUMPY_RANDOM = RandomState(MT19937)
Traceback (most recent call last):
  File "run.py", line 27, in <module>
    r.run()
  File "/home/azureuser/powerful-benchmarker/src/powerful_benchmarker/runners/single_experiment_runner.py", line 18, in run
    return self.run_new_experiment_or_resume(self.YR)
  File "/home/azureuser/powerful-benchmarker/src/powerful_benchmarker/runners/single_experiment_runner.py", line 33, in run_new_experiment_or_resume
    return self.start_experiment(args)
  File "/home/azureuser/powerful-benchmarker/src/powerful_benchmarker/runners/single_experiment_runner.py", line 22, in start_experiment
    run_output = api_parser.run()
  File "/home/azureuser/powerful-benchmarker/src/powerful_benchmarker/api_parsers/base_api_parser.py", line 11, in run
    self.make_dir()
  File "/home/azureuser/powerful-benchmarker/src/powerful_benchmarker/api_parsers/folder_creator.py", line 14, in make_dir
    c_f.makedir_if_not_there(self.experiment_folder)
  File "/home/azureuser/powerful-benchmarker/src/powerful_benchmarker/utils/common_functions.py", line 55, in makedir_if_not_there
    os.makedirs(dir_name)
  File "/anaconda/envs/metric_bench/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/anaconda/envs/metric_bench/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/content'
```

**Comment by KevinMusgrave** [comment]
Good point, though this is mentioned [in the documentation](https://kevinmusgrave.github.io/powerful-benchmarker/#getting-started), it could be made clearer.

**Comment by usuyama** [comment]
How about changing the first/basic command example to something like this?

```
python run.py --experiment_name test1 \
                       --root_experiment_folder experiments \
                       --dataset {CUB200: {download: True}}
```

It's minor, but I think a little more friction-less for trying this library for the first time.

**Comment by KevinMusgrave** [comment]
I changed the default path in run.py to "experiments"
