### ISSUE TITLE
Cross Batch Memory error

### ISSUE THREAD

**Issue by atkvb** [KevinMusgrave/powerful-benchmarker#82]
When running an experiment involving the Cross Batch Memory I encounter this error:

```
Traceback (most recent call last):
  File "run.py", line 27, in <module>
    r.run()
  File "/home/.../python3.7/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 18, in run
    return self.run_new_experiment_or_resume(self.YR)
  File "/home/.../python3.7/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 33, in run_new_experiment_or_resume
    return self.start_experiment(args)
  File "/home/.../python3.7/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 22, in start_experiment
    run_output = api_parser.run()
  File "/home/.../python3.7/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 18, in run
    return self.run_train_or_eval()
  File "/home/.../python3.7/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 28, in run_train_or_eval
    self.run_for_each_split_scheme()
  File "/home/.../python3.7/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 49, in run_for_each_split_scheme
    self.set_models_optimizers_losses()
  File "/home/.../python3.7/site-packages/powerful_benchmarker/api_parsers/getter_and_setter.py", line 47, in set_models_optimizers_losses
    self.loss_funcs = self.get_loss_funcs()
  File "/home/.../python3.7/site-packages/powerful_benchmarker/api_parsers/getter_and_setter.py", line 150, in get_loss_funcs
    return self.factories["loss"].create(named_specs=self.args.loss_funcs, **self.all_kwargs("loss_funcs", kwargs))
  File "/home/.../python3.7/site-packages/powerful_benchmarker/factories/base_factory.py", line 22, in create
    output[k] = self._create(named_specs, k, kwargs, per_name_kwargs)
  File "/home/.../python3.7/site-packages/powerful_benchmarker/factories/base_factory.py", line 40, in _create
    return creator_func(v, **final_kwargs)
  File "/home/.../python3.7/site-packages/powerful_benchmarker/factories/loss_factory.py", line 26, in _create_general
    loss_params["loss"] = self.create(loss_params["loss"])
  File "/home/.../python3.7/site-packages/powerful_benchmarker/factories/base_factory.py", line 31, in create
    return self._create_general(specs, **kwargs)
TypeError: _create_general() missing 1 required positional argument: 'num_classes'
```

```
python run.py \
--experiment_name test1 \
--loss_funcs {metric_loss~OVERRIDE~: {CrossBatchMemory: \
{loss: {TripletMarginLoss: {margin: 0.01}}, \
embedding_size: 128}}}
```

config_loss_and_miners.yaml
```
loss_funcs:
  metric_loss:
    CrossBatchMemory:
      loss:
        TripletMarginLoss:
          margin: 0.01
      embedding_size: 128
sampler:
  MPerClassSampler:
    m: 4
mining_funcs: {}
```

**Comment by KevinMusgrave** [comment]
Sorry about that. Can you try adding this code to run.py?

```python
from powerful_benchmarker.factories import LossFactory

class FixedLossFactory(LossFactory):
    def _create_general(self, loss_type, num_classes=None):
        super()._create_general(loss_type, num_classes)


# at the bottom of run.py
r = runner(**(args.__dict__))
r.register("factory", FixedLossFactory)
r.run()
```

Then add this flag to the command line:
```
--factories {loss~OVERRIDE~: {FixedLossFactory: {}}}
```

**Comment by atkvb** [comment]
Now I get another error:

```
INFO:root:Getting split: Test50_50_Partitions4_0 / train / length 4462 / using train transform
INFO:root:Creating end_of_epoch_hook
INFO:root:Getting split: Test50_50_Partitions4_0 / val / length 1402 / using eval transform
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    r.run()
  File "/home/.../runners/single_experiment_runner.py", line 18, in run
    return self.run_new_experiment_or_resume(self.YR)
  File "/home/.../runners/single_experiment_runner.py", line 33, in run_new_experiment_or_resume
    return self.start_experiment(args)
  File "/home/.../runners/single_experiment_runner.py", line 22, in start_experiment
    run_output = api_parser.run()
  File "/home/.../api_parsers/base_api_parser.py", line 18, in run
    return self.run_train_or_eval()
  File "/home/.../api_parsers/base_api_parser.py", line 28, in run_train_or_eval
    self.run_for_each_split_scheme()
  File "/home/.../api_parsers/base_api_parser.py", line 49, in run_for_each_split_scheme
    self.set_models_optimizers_losses()
  File "/home/.../api_parsers/getter_and_setter.py", line 57, in set_models_optimizers_losses
    self.set_devices(self.models, self.loss_funcs, self.mining_funcs, self.optimizers)
  File "/home/.../api_parsers/getter_and_setter.py", line 200, in set_devices
    v.to(self.device)
AttributeError: 'NoneType' object has no attribute 'to'
```

**Comment by KevinMusgrave** [comment]
Whoops, I forgot to return the output. This should fix it:

```python
class FixedLossFactory(LossFactory):
    def _create_general(self, loss_type, num_classes=None):
        return super()._create_general(loss_type, num_classes)
```

**Comment by atkvb** [comment]
Now its working, thanks for your help!
