### ISSUE TITLE
AttributeError("module 'torchvision.datasets' has no attribute 'CUB200'")]

### ISSUE THREAD

**Issue by melgor** [KevinMusgrave/powerful-benchmarker#9]
Hi, I get an error while trying to run all framework. 
The configuration file are taken from `cub200_old_approach_triplet_batch_all `.
Not sure what goes wrong ( I have dataset downloaded and path are fine)
```
Loading faiss with AVX2 support.
WARNING:root:[FileNotFoundError(2, 'No such file or directory'), AttributeError("module 'torchvision.datasets' has no attribute 'CUB200'")]
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    run_new_experiment(YR, config_foldernames)
  File "run.py", line 87, in run_new_experiment
    return run(args)
  File "run.py", line 45, in run
    run_output = api_parser.run()
  File "/home/bartosz.ludwiczuk/CODE/powerful-benchmarker/api_parsers/base_api_parser.py", line 50, in run
    self.set_split_manager()
  File "/home/bartosz.ludwiczuk/CODE/powerful-benchmarker/api_parsers/base_api_parser.py", line 141, in set_split_manager
    chosen_dataset = self.pytorch_getter.get("dataset", yaml_dict=self.args.dataset, additional_params={"dataset_root":self.args.dataset_root})
  File "/home/bartosz.ludwiczuk/.conda/envs/powerful_benchmarker/lib/python3.7/site-packages/easy_module_attribute_getter/easy_module_attribute_getter.py", line 22, in get
    raise BaseException
BaseException
```

**Comment by KevinMusgrave** [comment]
Have you changed the "--dataset_root" command line argument in run.py?

**Comment by melgor** [comment]
Look like I had typo in ```dataset_root```.  Sorry for unnecessary issue.
