### ISSUE TITLE
Compatibility with latest pytorch-metric-learning library

### ISSUE THREAD

**Issue by aidinbii** [KevinMusgrave/powerful-benchmarker#91]
Thank you very much for your work! It is really good.
But currently it's not compatible with the latest version of pytorch-metric-learning 0.9.99

When running the example script: 
` !python run_example.py --experiment_name test3 
--dataset~OVERRIDE~ {CUB200: {download: False}}
 `
I get:
> Traceback (most recent call last):
  File "/storage/groups/peng/projects/aidin_Kenjis_project/power_benchmark_HCS/run_example.py", line 33, in <module>
    r.run()
  File "/home/icb/aidin.biibosunov/miniconda2/envs/hcs_env/lib/python3.9/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 18, in run
    return self.run_new_experiment_or_resume(self.YR)
  File "/home/icb/aidin.biibosunov/miniconda2/envs/hcs_env/lib/python3.9/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 33, in run_new_experiment_or_resume
    return self.start_experiment(args)
  File "/home/icb/aidin.biibosunov/miniconda2/envs/hcs_env/lib/python3.9/site-packages/powerful_benchmarker/runners/single_experiment_runner.py", line 22, in start_experiment
    run_output = api_parser.run()
  File "/home/icb/aidin.biibosunov/miniconda2/envs/hcs_env/lib/python3.9/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 18, in run
    return self.run_train_or_eval()
  File "/home/icb/aidin.biibosunov/miniconda2/envs/hcs_env/lib/python3.9/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 28, in run_train_or_eval
    self.run_for_each_split_scheme()
  File "/home/icb/aidin.biibosunov/miniconda2/envs/hcs_env/lib/python3.9/site-packages/powerful_benchmarker/api_parsers/base_api_parser.py", line 49, in run_for_each_split_scheme
    self.set_models_optimizers_losses()
  File "/home/icb/aidin.biibosunov/miniconda2/envs/hcs_env/lib/python3.9/site-packages/powerful_benchmarker/api_parsers/getter_and_setter.py", line 52, in set_models_optimizers_losses
    self.tester = self.get_tester()
  File "/home/icb/aidin.biibosunov/miniconda2/envs/hcs_env/lib/python3.9/site-packages/powerful_benchmarker/api_parsers/getter_and_setter.py", line 168, in get_tester
    return self.factories["tester"].create(self.args.tester, **self.all_kwargs("tester", kwargs))
  File "/home/icb/aidin.biibosunov/miniconda2/envs/hcs_env/lib/python3.9/site-packages/powerful_benchmarker/factories/base_factory.py", line 31, in create
    return self._create_general(specs, **kwargs)
  File "/home/icb/aidin.biibosunov/miniconda2/envs/hcs_env/lib/python3.9/site-packages/powerful_benchmarker/factories/tester_factory.py", line 21, in _create_general
    return tester(**tester_params)
TypeError: __init__() got an unexpected keyword argument 'reference_set'

While with the version pytorch-metric-learning 0.9.92 it runs as expected.

**Comment by KevinMusgrave** [comment]
Thanks for bringing this up. Unfortunately I'm currently busy with other projects, so I won't be able to fix this very soon.
