### ISSUE TITLE
Pretraining on source

### ISSUE THREAD

**Issue by pablopalafox** [KevinMusgrave/powerful-benchmarker#95]
Hi @KevinMusgrave! Thanks for this great repo :) 

Quick question: is it possible to pretrain on the source data only (sort of the "source-only model" from the paper)? I was trying as follows:

```
python main.py --experiment_name dann_experiment --dataset office31 --src_domains amazon --target_domains dslr --adapter DANNConfig --download_datasets --pretrain_on_src
```

but I must be doing something wrong, because I'm getting this error

```
Traceback (most recent call last):
  File "/home/pablo/projects/powerful-benchmarker/main.py", line 369, in <module>
    main(args)
  File "/home/pablo/projects/powerful-benchmarker/main.py", line 290, in main
    study.optimize(
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/optuna/study/study.py", line 400, in optimize
    _optimize(
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/optuna/study/_optimize.py", line 264, in _run_trial
    raise func_err
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/home/pablo/projects/powerful-benchmarker/main.py", line 291, in <lambda>
    lambda trial: objective(
  File "/home/pablo/projects/powerful-benchmarker/main.py", line 204, in objective
    best_score, best_epoch = meta_validator.run(
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/meta_validators/forward_only_validator.py", line 23, in run
    return adapter.run(**kwargs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/frameworks/ignite/ignite.py", line 178, in run
    self.trainer.run(dataloaders["train"], **trainer_kwargs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/ignite/engine/engine.py", line 704, in run
    return self._internal_run()
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/ignite/engine/engine.py", line 783, in _internal_run
    self._handle_exception(e)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/ignite/engine/engine.py", line 466, in _handle_exception
    raise e
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/ignite/engine/engine.py", line 753, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/ignite/engine/engine.py", line 854, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/ignite/engine/engine.py", line 466, in _handle_exception
    raise e
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/ignite/engine/engine.py", line 840, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/frameworks/ignite/ignite.py", line 58, in training_step
    return self.adapter.training_step(batch)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/adapters/base_adapter.py", line 101, in training_step
    losses, _ = self.hook({}, combined)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/base.py", line 48, in __call__
    x = self.call(losses, inputs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/base.py", line 195, in call
    return self.hook(*args, **kwargs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/base.py", line 48, in __call__
    x = self.call(losses, inputs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/utils.py", line 108, in call
    x = h(all_losses, all_inputs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/base.py", line 48, in __call__
    x = self.call(losses, inputs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/optimizer.py", line 49, in call
    losses, outputs = self.hook(losses, inputs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/base.py", line 48, in __call__
    x = self.call(losses, inputs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/utils.py", line 108, in call
    x = h(all_losses, all_inputs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/base.py", line 48, in __call__
    x = self.call(losses, inputs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/utils.py", line 108, in call
    x = h(all_losses, all_inputs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/base.py", line 48, in __call__
    x = self.call(losses, inputs)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/features.py", line 79, in call
    func(inputs, outputs, domain, in_keys)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/features.py", line 105, in mode_with_grad
    self.add_if_new(
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/hooks/features.py", line 132, in add_if_new
    c_f.add_if_new(outputs, full_key, output_vals, inputs, model_name, in_keys)
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/utils/common_functions.py", line 67, in add_if_new
    input_vals = [kwargs[k] for k in in_keys]
  File "/home/pablo/miniconda3/envs/pb/lib/python3.9/site-packages/pytorch_adapt/utils/common_functions.py", line 67, in <listcomp>
    input_vals = [kwargs[k] for k in in_keys]
KeyError: 'target_imgs'
```

Let me know if I'm just missing some flags? Thanks a lot!

**Comment by KevinMusgrave** [comment]
Hmm, maybe a mismatching version of pytorch-adapt? Anyway I'm going to be merging the dev branch into the master branch soon. If you switch to the dev branch, pip install the requirements again, and then take a look at this file for some example commands: https://github.com/KevinMusgrave/powerful-benchmarker/blob/dev/powerful_benchmarker/scripts/test.sh

For example, I think this should work for pretraining on the source domain:
```
python powerful_benchmarker/main.py --exp_name test_experiment0 --dataset mnist \
--src_domains mnist --adapter PretrainerConfig \
--download_datasets --num_trials 2 \
--max_epochs 20 --pretrain_on_src --validator src_accuracy \
--use_stat_getter
```

I don't have documentation on the dev branch yet.

**Comment by KevinMusgrave** [comment]
If you want to stay on the master branch, I think you need to use ```--adapter PretrainerConfig``` rather than ```DANNConfig```

**Comment by pablopalafox** [comment]
Got it, thanks a lot. Using `PretrainerConfig` works. I'll stay on master for now, but looking forward to the new changes!
